### ISSUE TITLE
PWM duty_u16 will be int

### ISSUE THREAD

**Issue by straga** [lvgl-micropython/lvgl_micropython#107]
line 541 display_driver_framework.py        

if self._backlight_on_state == STATE_PWM:
            self._backlight_pin.duty_u16(value / 100 * 65535)  # NOQA   need change ->  (value * 65535) // 100

**Comment by kdschlosser** [comment]
ooops... heh. 

Thanks..

**Comment by kdschlosser** [comment]
This is now fixed...
