### ISSUE TITLE
Need a simple keyboard example?

### ISSUE THREAD

**Issue by jd3096-mpy** [lvgl-micropython/lvgl_micropython#118]
How to use keypad_framework.py?Need an example.
LIke press GPIO 1 button to input letter a,GPIO 2 to move left and so on.

**Comment by kdschlosser** [comment]
the keypad framework has not yet been tested... care to be the guinea pig?

**Comment by jd3096-mpy** [comment]
> the keypad framework has not yet been tested... care to be the guinea pig?

Okay, I will look into how to write a keyboard driver and then post the code. Actually, I think there should be an 'examples' folder created in the repository to store common initialization routines, otherwise, it's easy for those who are not very familiar with lvgl and micropython to get stuck at the initialization step.

**Comment by kdschlosser** [comment]
now when you say "keyboard" driver you are meaning like a literal keyboard for a PC?

I just pushed an update to the keypad driver. That should fix an issue with it. 


The sdl_keyboard.SDLKeyboard is the only "keyboard" driver that is available. It should work how it is. I will compile it in a little bit to see if it work properly.

**Comment by jd3096-mpy** [comment]
I have successfully driven the keypad, but without using your framework; I wrote it directly. The method is roughly as follows: first, initialization.

```
kb_indev=lv.indev_create()
kb_indev.set_type(lv.INDEV_TYPE.KEYPAD)
kb_indev.set_read_cb(get_key)
kb_indev.set_group(group)
```

Group must be setd.

get_key is a callback function that points to the keypad hardware driver, and it is roughly in this format.

```
def get_key(indev,data):
    # input your keypad code
    data.state = 1  #1 for press 0 for released 
    data.key=keymap[keys]
```


This is not very difficult, and I did not use your framework.

**Comment by ThomasFarstrike** [comment]
The keypad framework had an issue, reported and patch attached here: https://github.com/lvgl-micropython/lvgl_micropython/issues/378
