### ISSUE TITLE
Building for ESP32 ESP32-S3-WROOM-1-N4R8

### ISSUE THREAD

**Issue by spienz** [lvgl-micropython/lvgl_micropython#141]
First sorry for the confusion.

Trying to bild for this Panel
(https://www.elecrow.com/esp32-display-5-inch-hmi-display-rgb-tft-lcd-touch-screen-support-lvgl.html)

with ESP32 ESP32-S3-WROOM-1-N4R8

Buil command:
![build](https://github.com/user-attachments/assets/3a0bb137-3c73-4fe2-89ff-76fa6098195f)

But i'm getting this error

`Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3820,len:0x105c
load:0x403c9700,len:0x4
load:0x403c9704,len:0xbd8
load:0x403cc700,len:0x2e30
entry 0x403c989c
E (422) quad_psram: PSRAM ID read error: 0x00ffffff, PSRAM chip not found or not supported, or wrong PSRAM line mode
E (423) esp_psram: PSRAM enabled but initialization failed. Bailing out.
LVGL MicroPython 1.23.0 on 2024-10-05; Generic ESP32S3 module with ESP32S3
Type "help()" for more information.`

any idea ?

THX

Regards 

Sebastian

**Comment by kdschlosser** [comment]
I am working on that now... Elecrow isn't exactly forth coming with the specifications for that board. There are configuration flags that can be set that will alter how the ram gets set up. Problem is I need to know what the ram is in order to set it up properly. That is what I am digging into.

according to Elecrow the MCU that is being used is the ESP32-S3-WROOM-1-N4R8

and according to Espressif that MCU has 4 MB of quad SPI flash and 8 MB of octal SPI RAM

looking at the error...

```
Build:Mar 27 2021 
rst:0x1 (POWERON), boot:0x8 (SPI_FAST_FLASH_BOOT) 
SPIWP:0xee 
mode:DIO, clock div:1 
load:0x3fce3820, len:0x105c 

load:0x403c9700,len:0x4 
load:0x403c9704,len:0xbd8 
load:0x403cc700,len:0x2e30 
entry 0x403c989c E (422) 
quad_psram: PSRAM ID read error: 0x00ffffff, PSRAM chip not found or not supported, or wrong PSRAM line mode E (423) esp_psram: PSRAM enabled but initialization failed. Bailing out. 

LVGL MicroPython 1.23.0 on 2024-10-05; Generic ESP32S3 module with ESP32S3 Type "help()" for more information.
```

I know what this is..

Do you get a REPL prompt? You should be...

at the REPL prompt type in the following...

```
import gc
gc.mem_free()
```

and tell me what the output is.

**Comment by kdschlosser** [comment]
OH... You should also be compiling using `BOARD_VARIANT=SPIRAM_OCT`

**Comment by spienz** [comment]
Hey,

thanks for reply....

the answer is 203152

I tried all variants of building

![build_vari](https://github.com/user-attachments/assets/04928fe4-5f34-4b01-9fb0-12457f85d2a9)

**Comment by kdschlosser** [comment]
I need you to use this explicit build command

```
python3 make.py esp32 BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT --flash-size=4
```

while the build is happening go into the `build` folder and copy the sdkconfig file and attach it to a post.

**Comment by spienz** [comment]
i got the file

[sdkconfig.txt](https://github.com/user-attachments/files/17267377/sdkconfig.txt)

**Comment by spienz** [comment]
i also had the original firmware from elecrow, its outdated, but maybe it could be helpful to get te right settings?

**Comment by kdschlosser** [comment]
are you setting the BOARD_VARIANT correctly?

It is `BOARD_VARIANT=SPIRAM_OCT` It looks like you have set it as`BOARD_VARIANT=SPIRAM=OCT` which is incorrect

**Comment by spienz** [comment]
OMG, your are right i tried all the time the wrong binary in my compiling vm i had booth.
Now it works 

THX

**Comment by kdschlosser** [comment]
so it is up and running?

**Comment by spienz** [comment]
hy, it looks like, no error, repl with no error, wifi is working, trying sd access but have to change the code because sdcard behavior is changed. 
Then i check the display.

**Comment by kdschlosser** [comment]
the SD card has been changed so that you are now able to use the SD Card on the same bus as a touch panel or a display. With vanilla MicroPython you have to have a dedicated SPI bus for the SD Card. There is no way to share the bus with anything else. 

I corrected that issue. You need to create an spi.Bus instance and then create an SDCard instance passing the spi.Bus instance to the constructor of the SDCard.

so you can have a single SPI bus and on that bus you can have an SDCard, touch panel, display and any other devices you want. This was not possible with the original MicroPython design.

The best part is it's all thread safe too and you do not have to worry about the CS pins as those are all handled internally for you. Just pass the pin number to whatever it is you are adding to the bus and it is all managed internally. Currently the only thing that is non blocking when transmitting is the display. I still have to add that ability to the other types of devices.

**Comment by spienz** [comment]
ok thanks for that, i will try to do it :-)

**Comment by spienz** [comment]
Build is running THX

**Comment by tedx** [comment]
I got this same board and built using:
python3 make.py esp32 clean BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT DISPLAY=rgb_display INDEV=gt911 --flash-size=8 CONFIG_SPIRAM_XIP_FROM_PSRAM=y

flashed the firmware and tried this code:

```
# LVGL Micropython demo for unix, MacOS or ESP32 board
from micropython import const  # NOQA

import lcd_bus
import task_handler
import lvgl as lv  # NOQA


_WIDTH = const(800)
_HEIGHT = const(480)

from i2c import I2C
import gt911
import rgb_display

_CTP_SCL = const(20)
_CTP_SDA = const(19)
#_CTP_IRQ = const(4)

_SD_MOSI = const(11)
_SD_SCK = const(12)
_SD_MISO = const(13)

_LCD_FREQ = const(15000000)

'''
_HSYNC_PULSE_WIDTH = const(10)
_HSYNC_BACK_PORCH = const(10)
_HSYNC_FRONT_PORCH = const(10)

_VSYNC_PULSE_WIDTH = const(10)
_VSYNC_BACK_PORCH = const(10)
_VSYNC_FRONT_PORCH = const(20)
'''
_HSYNC_PULSE_WIDTH = const(4)
_HSYNC_BACK_PORCH = const(43)
_HSYNC_FRONT_PORCH = const(8)

_VSYNC_PULSE_WIDTH = const(4)
_VSYNC_BACK_PORCH = const(12)
_VSYNC_FRONT_PORCH = const(8)

'''
_PCLK = const(7)
_HSYNC = const(46)
_VSYNC = const(3)
_DE = const(5)
'''
_PCLK = const(0)
_HSYNC = const(39)
_VSYNC = const(41)
_DE = const(40)

_DISP = None
_BCKL = None
_DRST = None

i2c_bus = I2C.Bus(
    host=1,
    scl=_CTP_SCL,
    sda=_CTP_SDA,
    freq=400000,
    use_locks=False
)

i2c_device = I2C.Device(
    i2c_bus,
    dev_id=gt911.I2C_ADDR,
    reg_bits=gt911.BITS
)
'''
  cfg.pin_d0  = GPIO_NUM_8; // B0
  cfg.pin_d1  = GPIO_NUM_3;  // B1
  cfg.pin_d2  = GPIO_NUM_46;  // B2
  cfg.pin_d3  = GPIO_NUM_9;  // B3
  cfg.pin_d4  = GPIO_NUM_1;  // B4

  cfg.pin_d5  = GPIO_NUM_5;  // G0
  cfg.pin_d6  = GPIO_NUM_6; // G1
  cfg.pin_d7  = GPIO_NUM_7;  // G2
  cfg.pin_d8  = GPIO_NUM_15;  // G3
  cfg.pin_d9  = GPIO_NUM_16; // G4
  cfg.pin_d10 = GPIO_NUM_4;  // G5

  cfg.pin_d11 = GPIO_NUM_45; // R0
  cfg.pin_d12 = GPIO_NUM_48; // R1
  cfg.pin_d13 = GPIO_NUM_47; // R2
  cfg.pin_d14 = GPIO_NUM_21; // R3
  cfg.pin_d15 = GPIO_NUM_14; // R4

  cfg.pin_henable = GPIO_NUM_40;
  cfg.pin_vsync   = GPIO_NUM_41;
  cfg.pin_hsync   = GPIO_NUM_39;
  cfg.pin_pclk    = GPIO_NUM_0;
  cfg.freq_write  = 15000000;
  '''
'''
_DATA15 = const(10)  # B7
_DATA14 = const(17)  # B6
_DATA13 = const(18)  # B5
_DATA12 = const(38)  # B4
_DATA11 = const(14)  # B3
_DATA10 = const(21)  # G7
_DATA9 = const(47)  # G6
_DATA8 = const(48)  # G5
_DATA7 = const(45)  # G4
_DATA6 = const(0)  # G3
_DATA5 = const(39)  # G2
_DATA4 = const(40)  # R7
_DATA3 = const(41)  # R6
_DATA2 = const(42)  # R5
_DATA1 = const(2)  # R4
_DATA0 = const(1)  # R3
'''
_DATA15 = const(1)  # B7
_DATA14 = const(9)  # B6
_DATA13 = const(46)  # B5
_DATA12 = const(3)  # B4
_DATA11 = const(8)  # B3
_DATA10 = const(4)  # G7
_DATA9 = const(16)  # G6
_DATA8 = const(15)  # G5
_DATA7 = const(7)  # G4
_DATA6 = const(6)  # G3
_DATA5 = const(5)  # G2
_DATA4 = const(14)  # R7
_DATA3 = const(21)  # R6
_DATA2 = const(47)  # R5
_DATA1 = const(48)  # R4
_DATA0 = const(45)  # R3

bus = lcd_bus.RGBBus(
    hsync=_HSYNC,
    vsync=_VSYNC,
    de=_DE,
    pclk=_PCLK,
    data0=_DATA0,
    data1=_DATA1,
    data2=_DATA2,
    data3=_DATA3,
    data4=_DATA4,
    data5=_DATA5,
    data6=_DATA6,
    data7=_DATA7,
    data8=_DATA8,
    data9=_DATA9,
    data10=_DATA10,
    data11=_DATA11,
    data12=_DATA12,
    data13=_DATA13,
    data14=_DATA14,
    data15=_DATA15,
    freq=_LCD_FREQ,
    hsync_front_porch=_HSYNC_FRONT_PORCH,
    hsync_back_porch=_HSYNC_BACK_PORCH,
    hsync_pulse_width=_HSYNC_PULSE_WIDTH,
    vsync_front_porch=_VSYNC_FRONT_PORCH,
    vsync_back_porch=_VSYNC_BACK_PORCH,
    vsync_pulse_width=_VSYNC_PULSE_WIDTH,
)



# buf1 = bus.allocate_framebuffer(int(_WIDTH * _HEIGHT * 2 / 20), lcd_bus.MEMORY_INTERNAL)

buf1 = bus.allocate_framebuffer(int(_WIDTH * _HEIGHT * 2 / 40), lcd_bus.MEMORY_INTERNAL)
buf2 = None
display = rgb_display.RGBDisplay(
    data_bus=bus,
    display_width=_WIDTH,
    display_height=_HEIGHT,
    frame_buffer1=buf1,
    frame_buffer2=buf2,
    color_space=lv.COLOR_FORMAT.RGB565,
    rgb565_byte_swap=True
)



display.set_power(True)
display.init()
display.set_backlight(100)
indev = gt911.GT911(i2c_device)

if indev.hw_size != (_WIDTH, _HEIGHT):
    fw_config = indev.firmware_config
    fw_config.width = _WIDTH
    fw_config.height = _HEIGHT
    fw_config.save()

    del fw_config

scrn = lv.screen_active()

# lv.refr_now(scrn.get_display())
scrn.set_style_bg_color(lv.color_hex(0xFF0000), 0)

slider1 = lv.slider(scrn)
slider1.set_size(200, 50)
slider1.align(lv.ALIGN.CENTER, 0, -100)

slider2 = lv.slider(scrn)
slider2.set_size(200, 50)
slider2.align(lv.ALIGN.CENTER, 0, 100)
slider2.set_value(100, 0)

label = lv.label(scrn)
label.set_text('HELLO WORLD!')
label.align(lv.ALIGN.CENTER, 0, -50)

th = task_handler.TaskHandler()



```
but it fails creating the gt911 device:

Traceback (most recent call last):
  File "<stdin>", line 183, in <module>
  File "gt911.py", line 83, in __init__
  File "gt911.py", line 103, in hw_reset
  File "gt911.py", line 50, in _write_reg
  File "i2c.py", line 123, in write_mem
  File "i2c.py", line 82, in writeto_mem
OSError: [Errno 116] ETIMEDOUT
>>> 

Any advice/direction you could give me to get this thing working?
