### ISSUE TITLE
no module named 'ST7735'

### ISSUE THREAD

**Issue by dcmcshan** [lvgl-micropython/lvgl_micropython#149]
I looked in README, didn't see any mention of this changing?

`
% python3 make.py esp32 clean BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT --flash-size=16 DISPLAY=ST7735 --usb-otg --dual-core-threads`

```
LVGL MicroPython 1.23.0 on 2024-10-12; Generic ESP32S3 module with Octal-SPIRAM with ESP32S3
Type "help()" for more information.
>>> import ST7735
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'ST7735'
```

**Comment by kdschlosser** [comment]
it's st7735 not ST7735

**Comment by dcmcshan** [comment]
Strange.  But this also doesn't work.  Did the API change entirely?  This has worked for many months...

```
Traceback (most recent call last):
  File "<stdin>", line 123, in <module>
  File "<stdin>", line 69, in __init__
AttributeError: 'module' object has no attribute 'ST7735R_Red'
```

**Comment by kdschlosser** [comment]
HAHAHA... I changed the API so you were leading all kinds of code that wasn't going to get used. 

There is no `ST7735R_Red` class anymore. 

```python
import st7735


display = st7735.ST7735(
    ...
)

display.init(st7735.TYPE_R_RED)
```

That will get ya going.

**Comment by dcmcshan** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "MCT_DISPLAY.py", line 49, in <module>
ImportError: no module named 'st7735'

Did this change back?
