### ISSUE TITLE
WT32-SC01 (not PLUS) with ESP32 (not S3)

### ISSUE THREAD

**Issue by picpic020960** [lvgl-micropython/lvgl_micropython#150]
Bonjour Kevin ,
This vidéo for three issues : 
1 - 'hello world' IS inversed
2 - the scroll IS inverted
[3 - how to control the backlight]
3 - are the colors rights ?
St7796 with ft6x06 (typo on CHIP_ID in ft6x06.py ?)
Thanks for help
(After this , return to unix port)
https://github.com/user-attachments/assets/c1869a39-ac58-43c0-bb15-db4584edc13e

Édit : OK for backlight : backlight_on_state=st7796.STATE_PWM,

**Comment by kdschlosser** [comment]
damned 7796 issues. This single display IC is going to be the bane of my existence.

I can fix the reversed text, that's not too big of an issue.

there are 2 possible things that can fix the touch.. The first is trying to set the startup rotation of the display.


```python
import ft6x06

touch = ft6x06.FT6x06(
    ...
    startup_rotation=pointer_framework.lv.DISPLAY_ROTATION._180
)
```

If that doesn't correct the problem you can do a display calibration and that should fix it. 

```python
import ft6x06

touch = ft6x06.FT6x06(
    ...
)

if not touch.is_calibrated:
    touch.calibrate()

```

for the time being to correct the problem with the text being backwards... point the display at a mirror and look at the mirror... :smile:, I'm joking...

Until I am able to get around to updating the driver I am going to have you override part of the display driver...

```python

import st7796

st7796.ST7796._ORIENTATION_TABLE = (0x40, 0xE0, 0x80, 0x20)

# create the driver as usual.
```

**Comment by picpic020960** [comment]
Bonjour Kevin,
Calibrate and _ORIENTATION_TABLE works fine
Thank's

On the video, are the colors rights ?
Only this lines about colors in script :
```
color_space=lv.COLOR_FORMAT.RGB565,
    color_byte_order=st7796.BYTE_ORDER_BGR,
    rgb565_byte_swap=True,

```
And 
```
scrn.set_style_bg_color(lv.color_hex(0x000000), 0)
```

**Comment by picpic020960** [comment]
Kevin ,
Tryed this examples (lvgl v8)
[https://github.com/lvgl/lvgl/blob/4d96c27ce35dd2ea6b34926f24a647e7ea7c4b0c/examples/widgets/slider/lv_example_slider_1.py]
But the slider not respond 
You confirm ?

**Comment by kdschlosser** [comment]
you cannot use lvgl8 code it's not going to work..

**Comment by kdschlosser** [comment]
and for the display you are using you should have the color byte order set to RGB and set the rgb565 byte swap to True

**Comment by picpic020960** [comment]
Thank's Kevin
