### ISSUE TITLE
LV debug from build

### ISSUE THREAD

**Issue by dcmcshan** [lvgl-micropython/lvgl_micropython#177]
Is there a way to enable LVGL debug from the build command?  In lv_conf.h, we want to set:

```
#define LV_USE_LOG 1
#define LV_LOG_LEVEL LV_LOG_LEVEL_DEBUG
```

**Comment by kdschlosser** [comment]
not from the command line. You can edit `lib/lv_conf.h` to turn it on and off.

**Comment by dcmcshan** [comment]
fair enough
