### ISSUE TITLE
esp32 rgb_bus.c miss a ;

### ISSUE THREAD

**Issue by cscscheng** [lvgl-micropython/lvgl_micropython#182]
diff --git a/ext_mod/lcd_bus/esp32_src/rgb_bus.c b/ext_mod/lcd_bus/esp32_src/rgb_bus.c
index bcd5701..328cb1e 100644
--- a/ext_mod/lcd_bus/esp32_src/rgb_bus.c
+++ b/ext_mod/lcd_bus/esp32_src/rgb_bus.c
@@ -56,7 +56,7 @@
         rgb_panel_t *rgb_panel = __containerof(panel, rgb_panel_t, base);
         mp_lcd_rgb_bus_obj_t *self = (mp_lcd_rgb_bus_obj_t *)user_ctx;

-        void *curr_buf = rgb_panel->fbs[rgb_panel->cur_fb_index]
+        void *curr_buf = rgb_panel->fbs[rgb_panel->cur_fb_index];

         if (self->view2 != NULL && self->last_buf != curr_buf) {
             self->last_buf = curr_buf;
diff --git a/lib/esp-idf b/lib/esp-idf
--- a/lib/esp-idf
+++ b/lib/esp-idf
@@ -1 +1 @@
-Subproject commit 11eaf41b37267ad7709c0899c284e3683d2f0b5e
+Subproject commit 11eaf41b37267ad7709c0899c284e3683d2f0b5e-dirty
diff --git a/lib/micropython b/lib/micropython
--- a/lib/micropython
+++ b/lib/micropython
@@ -1 +1 @@
-Subproject commit d7d77d91becd0716ac1672c92652d9dd72ec613f
+Subproject commit d7d77d91becd0716ac1672c92652d9dd72ec613f-dirty

**Comment by kdschlosser** [comment]
TY for reporting this. It is now fixed.
