### ISSUE TITLE
Cannot create SPI instance on ESP32 S3

### ISSUE THREAD

**Issue by MussabMehboob** [lvgl-micropython/lvgl_micropython#211]
I am using an ESP32 S3 with PSRAM 8 MB and flash 16 MB. I want to test the LVGL on ST 7789(240*240) but I am seeing this error when I am creating an SPI instance in thonny.
```
from machine import SPI, Pin
from micropython import const

import lcd_bus
import st7789
import lvgl


_WIDTH = const(240)
_HEIGHT = const(240)


_SPI_HOST = const(2)
_SPI_SCK = const(10)
_SPI_MOSI = const(11)
_SPI_MISO = const(12)

_LCD_FREQ = const(400_000)
_LCD_DC = const(8)
_LCD_CS = const(9)
_LCD_RST = const(14)
_LCD_BACKLIGHT = const(2)


spi_bus = SPI(
    _SPI_HOST,
    _LCD_FREQ,
    mosi=_SPI_MOSI,
    miso=_SPI_MISO,
    sck=_SPI_SCK,
    cs=_LCD_CS
)

display_bus = lcd_bus.SPIBus(
    spi_bus=spi_bus,
    freq=_LCD_FREQ,
    dc=_LCD_DC,
    cs=_LCD_CS
)

    
display = st7789.ST7789(
    data_bus=display_bus,
    display_width=_WIDTH,
    display_height=_HEIGHT,
    backlight_pin=_BL,
    color_space=lv.COLOR_FORMAT.RGB565,
    color_byte_order=st7796.BYTE_ORDER_RGB,
    rgb565_byte_swap=True,
)
MPY: soft reboot
Traceback (most recent call last):
  File "boot.py", line 30, in <module>
TypeError: can't create 'SPI' instances
Traceback (most recent call last):
  File "<stdin>", line 30, in <module>
TypeError: can't create 'SPI' instances
```
I am building with this command:

`python3 make.py esp32 BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT DISPLAY=st7789 INDEV=gt911 --flash-size=16`

I even tried using SoftSPI that worked with the compilation but I started getting memory initialization errors.I have tried to resolve those issues as said in the issue#66(https://github.com/lvgl-micropython/lvgl_micropython/issues/66) but it didn't worked for me.
Thank you!

**Comment by kdschlosser** [comment]
This is wrong.

```
spi_bus = SPI(
    _SPI_HOST,
    _LCD_FREQ,
    mosi=_SPI_MOSI,
    miso=_SPI_MISO,
    sck=_SPI_SCK,
    cs=_LCD_CS
)
```

it should read

```
spi_bus = SPI.Bus(
    host=_SPI_HOST,
    freq=_LCD_FREQ,
    mosi=_SPI_MOSI,
    miso=_SPI_MISO,
    sck=_SPI_SCK,
    cs=_LCD_CS
)
```

**Comment by MussabMehboob** [comment]
Is having this error normal while compiling for ESP32 s3?
`[1954/1962] Building C object CMakeFiles/micropython.elf.dir/home/mussab/Desktop/lvgl_micropython/ex[1955/1962] Building C object CMakeFiles/micropython.elf.dir/home/mussab/Desktop/lvgl_micropython/ex[1956/1962] Building C object CMakeFiles/micropython.elf.dir/home/mussab/Desktop/lvgl_micropython/ex[1957/1962] Building C object CMakeFiles/micropython.elf.dir/home/mussab/Desktop/lvgl_micropython/ex[1958/1962] Building C object CMakeFiles/micropython.elf.dir/home/mussab/Desktop/lvgl_micropython/li[1959/1962] Building C object CMakeFiles/micropython.elf.dir/home/mussab/Desktop/lvgl_micropython/li[1960/1962] Linking CXX executable micropython.elf                                                  [1961/1962] Generating binary image from built executable
esptool.py v4.8.1
Creating esp32s3 image...
Merged 2 ELF sections
Successfully created esp32s3 image.
Generated /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/micropython.bin
[1962/1962] cd /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/esp-idf/esptool_py && /root/.espressif/python_env/idf5.2_py3.10_env/bin/python /home/mussab/Desktop/esp-idf-v5.2.1/components/partition_table/check_sizes.py --offset 0x8000 partition --type app /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/partition_table/partition-table.bin /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/micropython.bin
FAILED: esp-idf/esptool_py/CMakeFiles/app_check_size /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/esp-idf/esptool_py/CMakeFiles/app_check_size
cd /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/esp-idf/esptool_py && /root/.espressif/python_env/idf5.2_py3.10_env/bin/python /home/mussab/Desktop/esp-idf-v5.2.1/components/partition_table/check_sizes.py --offset 0x8000 partition --type app /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/partition_table/partition-table.bin /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/micropython.bin
Error: app partition is too small for binary micropython.bin size 0x25a3c0:
- Part 'factory' 0/0 @ 0x10000 size 0x25a000 (overflow 0x3c0)
ninja: build stopped: subcommand failed.
-e See https://github.com/micropython/micropython/wiki/Build-Troubleshooting
make: Leaving directory '/home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32'
ninja failed with exit code 1, output of the command is in the /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/log/idf_py_stderr_output_45703 and /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/log/idf_py_stdout_output_45703
make: *** [Makefile:66: all] Error 1


***** Resizing Partition *****

***** Running build again *****

make: Entering directory '/home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32'
idf.py -D MICROPY_BOARD=ESP32_GENERIC_S3 -D MICROPY_BOARD_DIR="/home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/boards/ESP32_GENERIC_S3" -DUSER_C_MODULES=../../../../../ext_mod/micropython.cmake -D MICROPY_FROZEN_MANIFEST=/home/mussab/Desktop/lvgl_micropython/build/manifest.py -D MICROPY_BOARD_VARIANT=SPIRAM_OCT -B build-ESP32_GENERIC_S3-SPIRAM_OCT build || (echo -e "See \033[1;31mhttps://github.com/micropython/micropython/wiki/Build-Troubleshooting\033[0m"; false)
Executing action: all (aliases: build)
Running ninja in directory /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT
Executing "ninja all"...
-- Building ESP-IDF components for target esp32s3
NOTICE: Processing 4 dependencies:
NOTICE: [1/4] espressif/esp_tinyusb (1.0.3)
NOTICE: [2/4] espressif/mdns (1.1.0)
NOTICE: [3/4] espressif/tinyusb (0.17.0~1)
NOTICE: [4/4] idf (5.2.1)
-- Project sdkconfig file /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/sdkconfig
Loading defaults file /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/sdkconfig.combined...
/home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/sdkconfig.combined:100 CONFIG_ESP32_WIFI_IRAM_OPT was replaced with CONFIG_ESP_WIFI_IRAM_OPT
/home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/sdkconfig.combined:101 CONFIG_ESP32_WIFI_RX_IRAM_OPT was replaced with CONFIG_ESP_WIFI_RX_IRAM_OPT
/home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/sdkconfig.combined:148 CONFIG_BT_NIMBLE_TASK_STACK_SIZE was replaced with CONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE
/tmp/kconfgen_tmp1sjvpjlj:167 line was updated to CONFIG_ESPTOOLPY_FLASHSIZE_4MB=n
/tmp/kconfgen_tmp1sjvpjlj:169 line was updated to CONFIG_ESPTOOLPY_FLASHSIZE_16MB=n
/tmp/kconfgen_tmp1sjvpjlj:173 line was updated to CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_40=n
/tmp/kconfgen_tmp1sjvpjlj:174 line was updated to CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_80=n
/tmp/kconfgen_tmp1sjvpjlj:175 line was updated to CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_160=n
/tmp/kconfgen_tmp1sjvpjlj:179 line was updated to CONFIG_SPIRAM_MODE_QUAD=n
-- App "micropython" version: d7d77d9-dirty  
-- Adding linker script /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/esp-idf/esp_system/ld/memory.ld
-- Adding linker script /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_system/ld/esp32s3/sections.ld.in
-- Adding linker script /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_rom/esp32s3/ld/esp32s3.rom.ld
-- Adding linker script /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_rom/esp32s3/ld/esp32s3.rom.api.ld
-- Adding linker script /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_rom/esp32s3/ld/esp32s3.rom.libgcc.ld
-- Adding linker script /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_rom/esp32s3/ld/esp32s3.rom.newlib.ld
-- Adding linker script /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_rom/esp32s3/ld/esp32s3.rom.version.ld
-- Adding linker script /home/mussab/Desktop/esp-idf-v5.2.1/components/soc/esp32s3/ld/esp32s3.peripherals.ld
Including User C Module(s) from ../../../../../ext_mod/micropython.cmake
Found User C Module(s): usermod_lcd_bus, usermod_lvgl, lvgl_interface, usermod_lcd_utils
-- Components: app_trace app_update bootloader bootloader_support bt cmock console cxx driver efuse esp-tls esp_adc esp_app_format esp_bootloader_format esp_coex esp_common esp_eth esp_event esp_gdbstub esp_hid esp_http_client esp_http_server esp_https_ota esp_https_server esp_hw_support esp_lcd esp_local_ctrl esp_mm esp_netif esp_netif_stack esp_partition esp_phy esp_pm esp_psram esp_ringbuf esp_rom esp_system esp_timer esp_wifi espcoredump espressif__esp_tinyusb espressif__mdns espressif__tinyusb esptool_py fatfs freertos hal heap http_parser idf_test ieee802154 json log lwip main_esp32s3 mbedtls mqtt newlib nvs_flash nvs_sec_provider openthread partition_table perfmon protobuf-c protocomm pthread sdmmc soc spi_flash spiffs tcp_transport touch_element ulp unity usb vfs wear_levelling wifi_provisioning wpa_supplicant xtensa
-- Component paths: /home/mussab/Desktop/esp-idf-v5.2.1/components/app_trace /home/mussab/Desktop/esp-idf-v5.2.1/components/app_update /home/mussab/Desktop/esp-idf-v5.2.1/components/bootloader /home/mussab/Desktop/esp-idf-v5.2.1/components/bootloader_support /home/mussab/Desktop/esp-idf-v5.2.1/components/bt /home/mussab/Desktop/esp-idf-v5.2.1/components/cmock /home/mussab/Desktop/esp-idf-v5.2.1/components/console /home/mussab/Desktop/esp-idf-v5.2.1/components/cxx /home/mussab/Desktop/esp-idf-v5.2.1/components/driver /home/mussab/Desktop/esp-idf-v5.2.1/components/efuse /home/mussab/Desktop/esp-idf-v5.2.1/components/esp-tls /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_adc /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_app_format /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_bootloader_format /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_coex /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_common /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_eth /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_event /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_gdbstub /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_hid /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_http_client /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_http_server /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_https_ota /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_https_server /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_hw_support /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_lcd /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_local_ctrl /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_mm /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_netif /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_netif_stack /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_partition /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_phy /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_pm /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_psram /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_ringbuf /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_rom /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_system /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_timer /home/mussab/Desktop/esp-idf-v5.2.1/components/esp_wifi /home/mussab/Desktop/esp-idf-v5.2.1/components/espcoredump /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/managed_components/espressif__esp_tinyusb /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/managed_components/espressif__mdns /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/managed_components/espressif__tinyusb /home/mussab/Desktop/esp-idf-v5.2.1/components/esptool_py /home/mussab/Desktop/esp-idf-v5.2.1/components/fatfs /home/mussab/Desktop/esp-idf-v5.2.1/components/freertos /home/mussab/Desktop/esp-idf-v5.2.1/components/hal /home/mussab/Desktop/esp-idf-v5.2.1/components/heap /home/mussab/Desktop/esp-idf-v5.2.1/components/http_parser /home/mussab/Desktop/esp-idf-v5.2.1/components/idf_test /home/mussab/Desktop/esp-idf-v5.2.1/components/ieee802154 /home/mussab/Desktop/esp-idf-v5.2.1/components/json /home/mussab/Desktop/esp-idf-v5.2.1/components/log /home/mussab/Desktop/esp-idf-v5.2.1/components/lwip /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/main_esp32s3 /home/mussab/Desktop/esp-idf-v5.2.1/components/mbedtls /home/mussab/Desktop/esp-idf-v5.2.1/components/mqtt /home/mussab/Desktop/esp-idf-v5.2.1/components/newlib /home/mussab/Desktop/esp-idf-v5.2.1/components/nvs_flash /home/mussab/Desktop/esp-idf-v5.2.1/components/nvs_sec_provider /home/mussab/Desktop/esp-idf-v5.2.1/components/openthread /home/mussab/Desktop/esp-idf-v5.2.1/components/partition_table /home/mussab/Desktop/esp-idf-v5.2.1/components/perfmon /home/mussab/Desktop/esp-idf-v5.2.1/components/protobuf-c /home/mussab/Desktop/esp-idf-v5.2.1/components/protocomm /home/mussab/Desktop/esp-idf-v5.2.1/components/pthread /home/mussab/Desktop/esp-idf-v5.2.1/components/sdmmc /home/mussab/Desktop/esp-idf-v5.2.1/components/soc /home/mussab/Desktop/esp-idf-v5.2.1/components/spi_flash /home/mussab/Desktop/esp-idf-v5.2.1/components/spiffs /home/mussab/Desktop/esp-idf-v5.2.1/components/tcp_transport /home/mussab/Desktop/esp-idf-v5.2.1/components/touch_element /home/mussab/Desktop/esp-idf-v5.2.1/components/ulp /home/mussab/Desktop/esp-idf-v5.2.1/components/unity /home/mussab/Desktop/esp-idf-v5.2.1/components/usb /home/mussab/Desktop/esp-idf-v5.2.1/components/vfs /home/mussab/Desktop/esp-idf-v5.2.1/components/wear_levelling /home/mussab/Desktop/esp-idf-v5.2.1/components/wifi_provisioning /home/mussab/Desktop/esp-idf-v5.2.1/components/wpa_supplicant /home/mussab/Desktop/esp-idf-v5.2.1/components/xtensa
-- Generating done 
-- Build files have been written to: /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT
[1/270] cd /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/esp-idf/main_esp32s3 && /usr/bin/cmake -E make_directory /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/genhdr && /root/.espressif/python_env/idf5.2_py3.10_env/bin/python /home/mussab/Desktop/lvgl_micropython/lib/micropython/py/makeversionhdr.py /home/mussab/Desktop/lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-S[2/12] Generating ../../partition_table/partition-table.bin                                                                                                         `

**Comment by kdschlosser** [comment]
The resizing is normal. 

I would need to see the whole script you are running along with the output from running that script in order to determine where the issue might be.

**Comment by kdschlosser** [comment]
I can also tell you that you are running an old version of the library as well.

you are running with esp-idf v5.2.1 when the version that is packaged with the library is 5.2.3.

In order to update properly you need to delete your local copy lvgl_micropython and clone it again.
