### ISSUE TITLE
compile error after LVGL upgrade step

### ISSUE THREAD

**Issue by h-milz** [lvgl-micropython/lvgl_micropython#212]
I figure I cloned too soon this morning. Pristine git clone, then

    python3 make.py esp32 BOARD=ESP32_GENERIC_S3 MICROPY_BOARD_VARIANT=SPIRAM_OCT --flash-size=4 DISPLAY=rgb_display INDEV=gt911

and then: 

>   File "/home/hm/local/lvgl_micropython/gen/fixed_gen_json.py", line 14, in <module>
>     import create_fake_lib_c  # NOQA
>     ^^^^^^^^^^^^^^^^^^^^^^^^
> ModuleNotFoundError: No module named 'create_fake_lib_c'

Looks as if you simply forgot git adding `gen/create_fake_lib_c.py`. 

BTW what stands "# NOQA" for?

**Comment by kdschlosser** [comment]
the `# NOQA` stops my IDE from checking a line for errors. some things are dynamic so and the IDE is not able to follow what is happening correctly in order for intellisense to work properly. So I disable the IDE's intellisense for that line using that marker.

**Comment by kdschlosser** [comment]
I wasn't done quite yet with the LVGL update. I have only done step one of it. I have to double check and see if I forgot to copy something over to the repo from the changes I made.

**Comment by kdschlosser** [comment]
OK I just finished updating the submodule for LVGL. It should be on version 9.2.2 now.

**Comment by kdschlosser** [comment]
This should now be fixed. the CI runs properly.

You need to install doxygen by running `apt-get install doxygen` if on a Debian based OS or `brew install doxygen` if running on Darwin (macOS)

**Comment by kdschlosser** [comment]
You need to do a fresh clone of the repo for the new IDF and LVGL versions to be used.

**Comment by kdschlosser** [comment]
You are all set with this? Everything is running properly?

**Comment by h-milz** [comment]
Yes. Sorry for not commenting - didn't work in the github Android app.
