### ISSUE TITLE
Build failes for esp32s3

### ISSUE THREAD

**Issue by VsevolodVasin** [lvgl-micropython/lvgl_micropython#222]
**Describe the bug**
The build fails when doing
python3 make.py esp32 BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT DISPLAY=rgb_display INDEV=FT6x36

If you are having a problem compiling paste the build output below. (NO SCREENSHOTS)

attached
[issue.txt](https://github.com/user-attachments/files/18136811/issue.txt).

**Comment by h-milz** [comment]
I compiled a couple of build today with the same config except the touch. You may want to  make a fresh cloned and start over to make sure everything is up to date. Also I believe the ft part should be written in small letters, not FT.

**Comment by ANARHIST1984** [comment]
Hello
I got same error.
Fresh system
<img width="1247" alt="Screenshot 2024-12-14 at 19 43 20" src="https://github.com/user-attachments/assets/10227927-c611-4a76-9684-42956d860bab" />

try with capital FT and small

**Comment by kdschlosser** [comment]
You have to read the readme. You need to install doxygen using brew.
