### ISSUE TITLE
Cannot use SPI() method

### ISSUE THREAD

**Issue by Mustigusti** [lvgl-micropython/lvgl_micropython#72]
I'm using an ESP32-WROVER-DEV v1.6 with ILI9341 LCD driver and XPT2046 touch driver. 
I tried building like you posted in the instructions for my custom build:

`python3 make.py esp32 submodules clean mpy_cross BOARD=ESP32_GENERIC BOARD_VARIANT=PSRAM DISPLAY=ili9341 INDEV=xpt2046 --flash-size=8 --optimize-size`

I can import lvgl, ili9341, xpt2046 and generally don't see a problem EXCEPT that I can't use the SPI() method.
I wrote:

`spi_bus = SPI(2, 1000, miso=19, mosi=23, sck=18, cs=5)`

but got the Error message:
`Traceback (most recent call last):
File “”, line 9, in
TypeError: can’t create ‘SPI’ instances`

Would really appreciate any inputs :)

I'm sorry your hand is injured right now so I don't expect a quick response and wish you a speedy recovery!

**Comment by kdschlosser** [comment]
read the README.md file in repo. It will explain why "machine.SPI" doesn't work
